Project/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Project.Models;
using System.Security.Claims;

namespace Project.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(User model)
        {
            bool isAuthenticated = DatabaseManipulator.CheckPassword(model.Username.ToLower(), model.Password);

            if (isAuthenticated)
            {
                var claims = new List<Claim> { new Claim(ClaimTypes.Name, model.Username.ToLower()) };

                if (model.IsAdmin == true)
                {
                    claims.Add(new Claim(ClaimTypes.Role, "admin"));
                }

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    AllowRefresh = true,
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                    IsPersistent = true
                };

                HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), authProperties);

                return RedirectToAction("Index", "Home");
            }

            // Add error message to ModelState
            ModelState.AddModelError("LoginError", "Invalid username or password.");
            return View("Index", model);
        }

    }
}

Project/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Project.Models;

namespace Project.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(User model)
        {

            if (!ModelState.IsValid)
            {
               return View( model);
            }


            // Pois ehkä, ei turvallinen, voi selvittää databasessa olevia käyttäjiä
            //if (DatabaseManipulator.CheckIfUsernameExist(model.Username))
            //{
            //    ModelState.AddModelError("LoginError", "Username already exists");
            //    return View(model);
            //}


            var newSalt = PasswordHash.createSalt();
            var hashedPassword = PasswordHash.HashPassword(model.Password, newSalt);


            var registerModel = new User
            {
                Username = model.Username.ToLower(),
                Password = hashedPassword,
                Salt = newSalt,
                IsAdmin = false

            };

            try
            { DatabaseManipulator.Register(registerModel); }
            catch (Exception e) {
               Console.WriteLine(e);
               return View(model); 
            }
            

            return RedirectToAction("Index", "Home");
        }
    }
}

Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseTracker666</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseTracker666.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fs-4 sticky-top shadow-sm text-white link-light">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto mb-1 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Login" asp-action="Index">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

    </header>

    @if (User.Identity.IsAuthenticated)

    {
        <div class="d-flex justify-content-end me-3">
            <p class="">Logged in as: <strong>@(User.Identity.Name)</strong></p>

        </div>
        <div class="d-flex justify-content-end me-3">
            <form asp-controller="Home" asp-action="Logout" method="get">
                <input type="submit" value="Logout" class="btn btn-dark" />
            </form>
        </div>
    }



    <div class="container">

        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExpenseTracker666 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>